---
title: "Analysis template"
author: "Harvard Chan Bioinformatics Core"
date: "`r Sys.Date()`"
format:
  html:
    code-fold: true
    code-tools: true
    code-overflow: wrap
    df-print: paged
    highlight-style: pygments
    number-sections: true
    self-contained: true
    theme: default
    toc: true
    toc-location: right
    toc-expand: false
    lightbox: true
params:
   #xxx: 
---

# Overview of this report

Template developed with materials in HBC training: xxx

Input

Output



```{r setup}
#| cache: FALSE
#| message: FALSE
#| warning: FALSE
#| echo: FALSE
#| eval: TRUE
stopifnot(R.version$major >= 4)
source("utils.R")
invisible(list2env(params, environment()))
```

```{r data-loadin}
dds <- inputRead(deseq_obj)
meta <- inputRead(deseq_meta)
```


# section 1


# Conclusions

# Methods

## R package references

```{r citations}
#| results='asis'
citation("ggplot2")
citation("dplyr")
```

## R session 

List and version of tools used for the xx report generation.

```{r}
sessionInfo()
```